# Generated by Django 4.0.4 on 2022-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='envs',
            field=models.ManyToManyField(to='main_app.env'),
        ),
    ]
